### ISSUE TITLE
Redis Cache Adapter fails when using socket

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-cache#103]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7601
User: @Moring
Created On: 2015-07-01T22:35:41Z
Updated At: 2015-11-06T22:06:36Z
Body
Bit of edge case:

Redis is attached to ZF2 cache via socket.

Doctrine redis cache via DoctrineModule\Cache\ZendStorageCache

It will fail intermittently (and always on Doctrine query error).

Error: 'Could not estabilish connection with Redis instance'

Does not occur with port connection.

If:  $redis->getTotalSpace() called against ZF2 Redis Cache Adapter before wrapped in DoctrineModule\Cache\ZendStorageCache -- no error.
---

**Comment by marc-mabe** [comment]
@Morning Does this issue still persist? I tried to reproduce this issue but I couldn't.

**Comment by Moring** [comment]
Can you please post up your test case/config? I will run it on the system with the issue, so I can get more detail.


Sent via mobile

-------- Original message --------

**Comment by marc-mabe** [comment]
@Moring I have configured Redis locally with socket (and set port to 0). Then I configured the unit tests to use this socket and fixed the tests to be able to run with different config see #118.

phpunit.xml
```
        <env name="TESTS_ZEND_CACHE_REDIS_ENABLED" value="true" />
        <env name="TESTS_ZEND_CACHE_REDIS_HOST" value="/var/run/redis/redis.sock" />
        <!-- <env name="TESTS_ZEND_CACHE_REDIS_PORT" value="6379" /> -->
        <env name="TESTS_ZEND_CACHE_REDIS_PASSWORD" value="" />
        <env name="TESTS_ZEND_CACHE_REDIS_DATABASE" value="false" />
```

Also I noticed a general issue with `<env name="TESTS_ZEND_CACHE_*_ENABLED" value="true" />` as this will be casted to PHP boolean `true` but the tests will check for string `true`. So you either set this as cli variable or you need to disable this check in tests.

Thanks

**Comment by Moring** [comment]
@marc-mabe Yes!!  Local socket does work under PHP: 7.0.12, Zend Cache 2.7.1.  It is great to Redis back again, thank you.  Did notice the documentation is a bit off, "lib_options" in the config, not "lib_option" for the serializer.

**Comment by marc-mabe** [comment]
Closing this one as it seems to work fine.

@Moring I have opened a PR for fixing the doc
Thanks
