### ISSUE TITLE
[3.0] Cache

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-cache#105]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

___
Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7211
User: @marc-mabe
Created On: 2015-02-12T19:03:23Z
Updated At: 2015-11-06T20:22:37Z
Body
I would like to "fix" some weird  logic from cache component.

* Reduce arguments by reference
* Move / Remove resource manager logic
  * the the cache storage adapter directly receives the basic resource (instances of `Memcache`, `Memcached`, `MongoClient`, `Redis`, `MongoCollection`, ...)
  * Where to move this logic to or should that be removed and leaving it up to the user?

Thoughts ?

ping @Ocramius @weierophinney 

___

**Comment by marc-mabe** [comment]
There are already issues open for this:
* Move / Remove resource manager logic = #24 
* Reduce arguments by reference = #8
