### ISSUE TITLE
How to overwrite adapter config?

### ISSUE THREAD

**Issue by Estigy** [zendframework/zend-cache#108]
I have a cache configuration array (defined in some module config file) that is handed over to StorageFactory::factory():

```php
array(
    'adapter' => array(
        'name' => 'filesystem',
        'options' => array(
            'cache_dir' => 'data/cache/navigation',
            'dir_level' => 0,
            'namespace' => '',
        ),
),
```

Now if I want to use another adapter on my local development machine, I insert the following code into my `local.php`

```php
array(
    'adapter' => array(
        'name' => 'blackhole',
        ),
),
```

This overwrites the adapter name, but does not work: All the other, already given, options are being pushed to the blackhole adapter, but the corresponding methods like `setCacheDir()` don't exist there.
(The BlackHole adapter ist just an example, the problem would be the same if you had configured Memcache but want to use Filecache locally.)

So how do you correctly define adapters together with their options in your global config files so they still can be overwritten in local config files?

Thanks in advance, Estigy

**Comment by Estigy** [comment]
In my opinion, either we only push those options to the adapter that the adapter can handle, or we push all options to the adapter but ignore the not-known methods (via an empty `__call()` method).

**Comment by weierophinney** [comment]
zend-stdlib provides a way to remove configuration via the class `Zend\Stdlib\ArrayUtils\MergeRemoveKey`. As an example, in your `local.php`, you would write it as follows:

```php
use Zend\Stdlib\ArrayUtils\MergeRemoveKey;

return [
    'caches' => [
	'cache-application' => [
	    'adapter' => [
	        'name' => 'blackhole',
	        'options' => new MergeRemoveKey(),
	    ],
	],
    ],
];
```

When configuration merging occurs, if that key exists, `ArrayUtils::merge()` will now remove the entry.

**Comment by marc-mabe** [comment]
Closing this as @weierophinney commented a working and clean solution
