### ISSUE TITLE
MongoDB auto-expire

### ISSUE THREAD

**Issue by ebeyrent** [zendframework/zend-cache#11]
MongoDB will auto-expire documents if an index is set on the expiration field:

db.cache.ensureIndex( { "expires": 1 }, { expireAfterSeconds: 3600 } )

It doesn't seem like this cache adapter supports this though.  What's the best way to implement this?  I was thinking that perhaps the internalSetItem() method could get the current indexes, and add the index if it doesn't exist.

**Comment by marc-mabe** [comment]
This can be configured behind the mongodb adapter as the adapter (or even the adapter specific resource manager) on selects the configured collection.

As you can see in `internalGetItem` / `internalSetItem` / ... the expire date will be stored using a mongo date under the property named `expires`. That means as reading the mongo documentation you have to set up the collection like the following and all should work fine:
`db.log_events.createIndex({"expires":1},{expireAfterSeconds:0})`

Indeed this should be documented if it's not already done.

**Comment by ebeyrent** [comment]
Agreed, it can be done external to the adapter, as a manual setup task.  I'm wondering if the adapter should create the index by default.  I ended up adding it to the `internalSetItem()` method, which worked perfectly.  

    protected function internalSetItem(& $normalizedKey, & $value)
    {
        $this->getMongoDbResource()->ensureIndex(
            array('expires' => 1),
            array('expireAfterSeconds' => $this->getOptions()->getTtl())
        );
        // ....
    }

**Comment by marc-mabe** [comment]
If you put it on set item there will be an additional request each time
