### ISSUE TITLE
Disable the repo wiki

### ISSUE THREAD

**Issue by Koopzington** [zendframework/zend-cache#110]
Since the docs are located elsewhere this repo's empty wiki should be disabled.

**Comment by marc-mabe** [comment]
@weierophinney @ezimuel ping

**Comment by Koopzington** [comment]
I asked mwop. He agreed and allowed me to open this issue on every repo I
could find.

Am 09.08.2016 23:27 schrieb "Marc Bennewitz" <notifications@github.com>:

**Comment by marc-mabe** [comment]
@Koopzington that's totally file for me but I just don't have permissions to do so ;)
That's why I ping @weierophinney

**Comment by weierophinney** [comment]
Done.
