### ISSUE TITLE
serializer not found

### ISSUE THREAD

**Issue by Perfect-Web** [zendframework/zend-cache#125]
no matter what i do i get 
```
 Class 'Zend\Serializer\Serializer' not found
```
this is with any version ^2.7

**Comment by froschdesign** [comment]
@Perfect-Web 
Add `zend-serializer` to the composer.json.[ It's suggested packages.](https://github.com/zendframework/zend-cache/blob/master/composer.json#L29)
You can find more infos about "suggest" at the [Composer docs](https://getcomposer.org/doc/04-schema.md#suggest).
