### ISSUE TITLE
Cache saved with wrong user

### ISSUE THREAD

**Issue by verschoof** [zendframework/zend-cache#127]
Hi,

I use a library that uses zend-cache. (https://github.com/psliwa/PHPPdf/issues/122)
Now, zend-cache is caching files into my cache location but with the wrong user.

Is there a way I can tell zend-cache that he has to write as another user?

**Comment by Ocramius** [comment]
@verschoof the user is determined by the user that starts the PHP process that creates the file, and cannot really be controlled on our side.

This would usually require a privileged call, or `root` privileges, and running PHP as `root` is generally a messed up idea: https://secure.php.net/manual/en/function.posix-setuid.php

**Comment by froschdesign** [comment]
@verschoof 
For the `Filesystem` adapter you can set [file and directory permissions](https://docs.zendframework.com/zend-cache/storage/adapter/#the-filesystem-adapter). (`zend-cache` uses PHP's [chmod](http://php.net/manual/de/function.chmod.php))
But no user. (see comment above)

**Comment by verschoof** [comment]
Alright thanks guys!
