### ISSUE TITLE
mongo support

### ISSUE THREAD

**Issue by naprstek** [zendframework/zend-cache#131]
Mongo adapter still uses old mongo library, while Zend\Session uses the new MonoDB library. Therefore is imposible to use Zend\Session and Zend\Cache with mongo storage at once.

Is there plan to adopt the new MongoDB for Zend\Cache?

**Comment by marc-mabe** [comment]
Yes it is but first there is a refactoring for v3 going on incl. rename the mongodb adapter to mongo as that what it is.

Afterward there is place for a new mongodb adapter.

**Comment by marc-mabe** [comment]
If you want to start working on that please check out my zend-cache-* repositories ;)

**Comment by weierophinney** [comment]
Available on develop branch now; will release with 2.8.0. We'll be moving all adapters to their own repos soon, but only v3 will require installing them via those packages.
