### ISSUE TITLE
When 2.8 will be released?

### ISSUE THREAD

**Issue by StudioMaX** [zendframework/zend-cache#145]
The latest tag 2.7.2 was released on 16 Dec 2016. Looks like this project is a bit outdated.
- PSR-6 (https://github.com/zendframework/zend-cache/pull/54) was merged to the `develop` branch on 8 Jun 2016, but doesn't merged into the `master` branch
- PSR-16 (https://github.com/zendframework/zend-cache/pull/126) Pull Request don't have any updates since 28 Jan 2017
- PHP 7.2 was released on 30 Nov 2017, and there are PR (https://github.com/zendframework/zend-cache/pull/141) for its support, which still doesn't merged

What's the current status of Zend\Cache?

I'm interested because I started moving the legacy project from Zend 1 to Zend 3 and found significant differences between Zend_Cache and Zend\Cache (cannot specify TTL per cache item). I would not like to write some type of wrappers for setItem()/getItem() when there are already PSR-6 and PSR-16, but which for some reason have not yet merged into the master branch.

**Comment by Ocramius** [comment]
Release is probably up to @marc-mabe here, as he's the gatekeeper :-)

**Comment by tnsoftbear** [comment]
Hi, is there any information regarding @marc-mabe 's release plans?

**Comment by Ocramius** [comment]
Usually depends on his free time ;-)

**Comment by marc-mabe** [comment]
Hi,

I noticed Matthew already some time ago that I have no more time and less interest into maintaining zend-cache and zend-serializer as of other private projects and I’m going into different focus of software engineering (big data / go / python / scala)

I’m still working and interested in developing PHP applications and contributions but much limited.

For zend-cache there are is a couple of work needed to clean thinks up and there there are splitted repos on my user for refactoring but I never found time to finish.

Would be great if someone could take over. I’m of course available to give some help.

**Comment by tnsoftbear** [comment]
Thanks for sad true about framework of Zend

**Comment by froschdesign** [comment]
@tnsoftbear 
Question to you: Is this your way of motivating people or supporting an open source project? And how does your statement help with this problem?

**Comment by weierophinney** [comment]
I will be working with @ezimuel after we get the Expressive 3 release out as well as various API-related middleware components completed to get these features for zend-cache completed.

@marc-mabe We'll reach out to you once we've begun; thanks for the update!

**Comment by tnsoftbear** [comment]
@froschdesign How could I motivate or support this module progress?

**Comment by Ocramius** [comment]
Step up by reviewing open issues and PRs, writing release notes and (once
you got your feet wet) joining the maintainers 👍

On 25 Jan 2018 00:48, "tnsoftbear" <notifications@github.com> wrote:

@froschdesign <https://github.com/froschdesign> How could I motivate or
support this module progress?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/zendframework/zend-cache/issues/145#issuecomment-360313190>,
or mute the thread

**Comment by weierophinney** [comment]
2.8.0 release will occur on Monday, 23 April 2018.
