### ISSUE TITLE
Add APCu adapter as feature replacement for Apc

### ISSUE THREAD

**Issue by DCMNMarc** [zendframework/zend-cache#23]
As of the old PHP extension [APC](http://pecl.php.net/package/APC) seems inactive and doesn't compile with PHP-5.6 / PHP-7 (PHP-5.4 should work but PHP-5.5 not tested) we can drop the adapter for it.

In fact the APC extension is inactive because of the PHP opcache and the possibility to store user data in the cache has been moved to [APCu](http://pecl.php.net/package/APCu) long time ago.

APC and APCu is nearly compatible on storing user data but in some cases it's not. The differences are already part of the Apc adapter.

To simplify the adapter a little bit and because it's no longer possible to use the old APC extension with the minimal required PHP version it makes sense to completely drop support for it.

Renaming the adapter from Apc to Apcu:
If I only take a look what the optimal way would look like it would make sense to also rename the Apc adapter to Apcu. With a deeper look the there are two cases where it could make confusion.
* The APCu extension comes with a BC safe version (the version that the current adapter supports only)
 * Even if it's compiled with BC to APC all APCu functionalities are available
 * -> from this POV it's fine
* HHVM comes with APC support for the old APC extension.
 * Does someone now if HHVM also supports APCu?

@weierophinney @ezimuel @Ocramius @Maks3w Thoughts?

**Comment by Ocramius** [comment]
The point of APCu is to make the switch to it transparent: do not change
the APC adapter unless there is an actual need for it, and the current
adapter works just fine with APCu.

**Comment by marc-mabe** [comment]
@Ocramius  The current adapter only works with APCu if compiled with the flag `--enable-apc-bc`

**Comment by Ocramius** [comment]
@marc-mabe which is the only reason why somebody would use `APCu` anyway? :|

**Comment by marc-mabe** [comment]
@Ocramius The APC extension is dead and it doesn't work with our out min requirements. The most common way to cache user data into shared memory is APCu but we only support APCu if it was compiled with the BC flag. I think it would be very good if we completely support APCu - not only in one outdated case.

Btw. the default option for this flag is to not compile it with for BC ;)

**Comment by Ocramius** [comment]
> Btw. the default option for this flag is to not compile it with for BC ;)

Yes, but no APCu installation that I saw so far uses APCu specific stuff: everyone just wants the BC compliant interface.

 > I think it would be very good if we completely support APCu - not only in one outdated case.

I'd rather ask @krakjoe what his plans are for 7.0 and APCu: he went for a full rewrite (multiple times, IIRC), so we better wait for something stable before jumping at it.

**Comment by krakjoe** [comment]
At some point, the APC compat stuff might be dropped, it's not so easy to improve, or document APCu because of the compatibility requirements. Currently there is a bc mode for 7, but it probably would be a good idea to switch to the apcu_* API functions in preparation for the time when the apc compat module is removed ...

**Comment by marc-mabe** [comment]
closed by 2cd809d
