### ISSUE TITLE
Discordance of Redis persistent_id typology between docs and tests

### ISSUE THREAD

**Issue by pensiero** [zendframework/zend-cache#4]
`persistent_id` of Redis adapter, [according to docs](http://framework.zend.com/manual/current/en/modules/zend.cache.storage.adapter.html#the-redis-adapter), should be something like `RDB` or `AOF`; however, in the [tests](https://github.com/zendframework/zend-cache/blob/master/test/Storage/Adapter/RedisResourceManagerTest.php#L102), the persistent_id that is setted is a generic number.

What is correct, and what is wrong?

**Comment by marc-mabe** [comment]
mh good question - in phpredis (https://github.com/phpredis/phpredis#pconnect-popen) this is simply documented as a string but this could also be wrong. Can you test it out what kind of type this should be please.

**Comment by pensiero** [comment]
Open an issue also on phpredis: https://github.com/phpredis/phpredis/issues/619

**Comment by pensiero** [comment]
@marc-mabe how can I test?

**Comment by pensiero** [comment]
Ok, @michael-grunder was very clear. So i'm going to PR the doc

**Comment by marc-mabe** [comment]
@pensiero thanks for the research! So the test should be fixed to simply pass a string instead of an integer as the integer will be casted to a string in this case.

**Comment by pensiero** [comment]
@marc-mabe do you think it's ok this way?

**Comment by pensiero** [comment]
Thanks :)
