### ISSUE TITLE
clearByTags in Filesystem adapter crashes when .tag file deleted during GlobIterator loop

### ISSUE THREAD

**Issue by skors** [zendframework/zend-cache#44]
Hi,

we see the following error when using Filesystem storage adapter and deleting a large set of object from cache with `clearByTags()` method.

```
// when file_locking is off in File Zend/Cache/Storage/Adapter/Filesystem.php in line 1363
file_get_contents(my_cache_dir/my_cached_object_4711.tag): failed to open stream: No such file or directory
// when file_locking is on in File Zend/Cache/Storage/Adapter/Filesystem.php in line 1327
fopen(my_cache_dir/my_cached_object_4711.tag): failed to open stream: No such file or directory
```

It is not that easy to reproduce but occurs as follows:

- the `GlobIterator` in `clearByTags()` looks for all .tag files which holds the cached item tags information
- while looping through these items, another process deletes one item (and its .tag file) which is also prior found by the `GlobIterator`
- `clearByTags` triggers an error at `$this->getFileContent($pathname)` because `fopen()` or `file_get_contents` try to open a non existing file (not existing anymore)

Should be simple be avoided by adding
```php
if (!file_exists($file)) { // or !$glob->valid()?
    continue;
}
```

to the foreach loop in `clearByTags()`, but is this right?

I also can submit a PR, but until now i do not have found a way to reproduce for a unit test

cheers

**Comment by skors** [comment]
This issue probably also occurs in the other clearBy* methods where the GlobIterator is used as well. There is no usage of the valid() method in these.

**Comment by marc-mabe** [comment]
hi @skors - thanks for your bug report!

This one is really hard to solve and test and it can happen on every function looping over different items.

A simple `file_exists` doesn't fully solve the issue as first the result of `file_exists` will be cached by PHP itself and calling `clear_stat_cache` would totally degree performance and secondly there is still a possible race condition between `file_exists` and reading the file.

A better solution would be to catch the error on reading the file and afterwords check if the reason of the error is a missing file. Than ignore the error in this case. For removing files there is already a the method `Filesystem::unlink` that works this way.

**Comment by skors** [comment]
@marc-mabe okay. I'll try to work on it and maybe you can take a review if i have understood you correctly

**Comment by marc-mabe** [comment]
Nice thanks

**Comment by marc-mabe** [comment]
@skors any news ?

**Comment by skors** [comment]
@marc-mabe yes, just give me a few days

**Comment by skors** [comment]
@marc-mabe please see bugfix/clear-by-tag_on_filesystem-storage branch at skors/zend-cache
https://github.com/skors/zend-cache/tree/bugfix/clear-by-tag_on_filesystem-storage

I've added tests which can reproduce the error now
