### ISSUE TITLE
PSR-6 wrapper?

### ISSUE THREAD

**Issue by kynx** [zendframework/zend-cache#46]
Has anyone done any work on a PSR-6 wrapper for zend-cache? I know the PSR still in review, but it would be darn handy...

**Comment by weierophinney** [comment]
Considering there are still a few proposed changes to the spec, we can't
incorporate such a wrapper in a stable version. Once the spec is accepted,
absolutely we'd like to do this.

**Comment by kynx** [comment]
Thanks for that. Yes, I appreciate it's not going to land in stable until accepted - was more wondering if anyone had a prototype they'd been working on. If not, I'll just have to see how itchy I get :wink:

**Comment by kynx** [comment]
Well, the itching got the better of me. My first stab at this is [over here](https://github.com/kynx/zend-cache-psr6) if anyone's interested. Still a [bunch of things](https://github.com/kynx/zend-cache-psr6/blob/master/TODO.md) to iron out, but more than happy to contribute this back when (surely not if?) PSR-6 finally gets accepted.

**Comment by kynx** [comment]
PSR-6 finally got accepted! 

There's some useful stuff in FIG's [cache-util](https://github.com/php-fig/cache-util) that I need to work into [my wrapper](https://github.com/kynx/zend-cache-psr6), and some thought to put into expiry / clearing / flushing. But if no one else has plans in progress I'll be happy to take a break from the mince pies over the next week or so :smile:

**Comment by marc-mabe** [comment]
@kynx #80 has been merged into develop now. Please can you update your PR and not allow adapters capability `lockOnExpire > 0` thanks!

**Comment by marc-mabe** [comment]
closed by cf35782
