### ISSUE TITLE
Travis: APC tests not running

### ISSUE THREAD

**Issue by marc-mabe** [zendframework/zend-cache#50]
I found out two reasons:

1) Installing the APCu extension fails on PHP < 7 as the last beta supports PHP 7 only
   `echo "yes\nno\n" | pecl -d preferred_state=beta install apcu || return 0`
2) It looks like the extension will not be automatically enabled by `pecl`

**Comment by Maks3w** [comment]
I guess we don't have any choice and the only option is lock the version
