### ISSUE TITLE
Broken Events v2 compatibility

### ISSUE THREAD

**Issue by bacinsky** [zendframework/zend-cache#71]
I think this just can`t work:
https://github.com/zendframework/zend-cache/blob/master/src/Storage/Adapter/AbstractAdapter.php#L193
https://github.com/zendframework/zend-eventmanager/blob/release-2.6.2/src/EventManager.php#L57

BTW, I'm not offending, just complaining, with the v3 oncoming this backward compatibility issues got worse directly, into masters. You know I can`t be happy with things like that. Spending time finding BC breaks in the ZF2 instead of doing work for my clients. I really appreciate your work but this is sad for me that the ZF2 is going like this.

**Comment by pobidowski** [comment]
Confirm

**Comment by bgaillard** [comment]
Hi we encountered the same problem after upgrading Zend-cache from version `2.5.3` to version `2.6.0`.

**Comment by simonbaudry** [comment]
Confirm as well on the version 2.6.0

**Comment by weierophinney** [comment]
@bacinsky We are trying very hard to test against both v2 and v3 APIs to ensure things going break; this particular line clearly didn't have a test case covering it. I'll get a fix our shortly, as there is a way to make this work on both versions. 

Thanks for the report!

**Comment by neoglez** [comment]
https://github.com/zendframework/zend-cache/issues/72 is a direct consequence of this break.

**Comment by weierophinney** [comment]
Those affected by this issue: can you please test the patch from #73? Tests pass against both event manager versions, and I added tests explicitly for the lazy-loading aspect, which should resolve the issue. However, I'd like verification from somebody affected.

**Comment by bgaillard** [comment]
Hi @weierophinney and thanks for your reactivity on this, I tested the patch and it seems to work.

**Comment by quintanilhar** [comment]
Hi @weierophinney, I also tested this patch and worked fine.

Waiting for the merge :)

Thank you!
