### ISSUE TITLE
SharedEventManager - first argument should be either a string or an integer

### ISSUE THREAD

**Issue by CreativeNative** [zendframework/zend-cache#75]
After updating from zendframework/zend-cache (2.5.3) to (2.6.0) I got error 

**array_key_exists(): The first argument should be either a string or an integer**
in File: .../vendor/zendframework/zend-eventmanager/src/SharedEventManager.php   Line: 153

    151:        public function getListeners($id, $event)
    152:        {
    153:            if (!array_key_exists($id, $this->identifiers)) {
    154:                return false;
    155:            }
    156:            return $this->identifiers[$id]->getListeners($event);
    157:        }

with arguments:

	$key	
	Zend\EventManager\SharedEventManager(1) ▼ {
	   identifiers protected => array(0) 
	}
	$search	
	array(4) ▼ {
	   "Zend\Mvc\Application" => Zend\EventManager\EventManager(4) ▼ {
		  events protected => array(1) ▼ {
			 bootstrap => Zend\Stdlib\PriorityQueue(3) { ... }
		  }
		  eventClass protected => "Zend\EventManager\Event" (23)
		  identifiers protected => array(1) ▼ [
			 0 => "Zend\Mvc\Application" (20)
		  ]
		  sharedManager protected => NULL
	   }
	   doctrine => Zend\EventManager\EventManager(4) ▼ {
		  events protected => array(1) ▼ {
			 "loadCli.post" => Zend\Stdlib\PriorityQueue(3) { ... }
		  }
		  eventClass protected => "Zend\EventManager\Event" (23)
		  identifiers protected => array(1) ▼ [
			 0 => "doctrine" (8)
		  ]
		  sharedManager protected => NULL
	   }
	   "Zend\Stdlib\DispatchableInterface" => Zend\EventManager\EventManager(4) ▼ {
		  events protected => array(1) ▼ {
			 dispatch => Zend\Stdlib\PriorityQueue(3) { ... }
		  }
		  eventClass protected => "Zend\EventManager\Event" (23)
		  identifiers protected => array(1) ▼ [
			 0 => "Zend\Stdlib\DispatchableInterface" (33)
		  ]
		  sharedManager protected => NULL
	   }
	   profiler => Zend\EventManager\EventManager(4) ▼ {
		  events protected => array(1) ▼ {
			 collected => Zend\Stdlib\PriorityQueue(3) { ... }
		  }
		  eventClass protected => "Zend\EventManager\Event" (23)
		  identifiers protected => array(1) ▼ [
			 0 => "profiler" (8)
		  ]
		  sharedManager protected => NULL
	   }
	}

Can someone help? -_-

**Comment by CreativeNative** [comment]
Sorry, is a duplicate of #71 and #72.

**Comment by weierophinney** [comment]
And fixed with #73, which released with 2.6.1 earlier today.
