### ISSUE TITLE
Segmentation Fault in RedisTest::testSetAndGetItemOfDifferentTypes

### ISSUE THREAD

**Issue by marc-mabe** [zendframework/zend-cache#88]

**Comment by marc-mabe** [comment]
The segfault happens on trying to store a `NULL` value and it has been fixed in [redis-2.2.7](https://pecl.php.net/package-info.php?package=redis&version=2.2.7) which was released in 2015-03-03

The problem here is that most distros are shipping an older version.

I see the following possibilities:
* Mark as `wontfix`
* increase minimum required redis extension version to 2.2.7
* check redis extension version and define the capability supported data types accordingly
* manually cast to `NULL` to string as this is what the current capability supported data types defines

@weierophinney @Maks3w @Ocramius @kynx  Thoughts ?

**Comment by Maks3w** [comment]
1. Does this affect to production code or only to tests? 

2. What redis extension version is distributed in those distributions? 

3. Is that version branch still supported by the vendor? 

About to transform null in a different type, definitely no as it breaks forward compatibility and breaks the developer expectations. 

If we conclude we can't raise the minimum version then we should throw Exception if null data type and bugged extension are used at the sametime. The exception should indicate the developer must update the extension, avoid to write null values or replace null values with any other value like string, integer,  etc

**Comment by kynx** [comment]
Of the distros I've got running:

- RHEL 5 (via EPEL): doesn't ship extension
- RHEL 6 & 7 (via EPEL): 2.2.7
- Ubuntu 14.04.4: 2.2.4
- Brew: 2.2.7

Would bumping the minimum version mean tests won't run in travis? That would be a pain.

**Comment by Maks3w** [comment]
IIRC there is a setting for use a most recent version of Ubuntu.

As far as I see only current Ubuntu LTS ship an older version. But Ubuntu has a large userbase and the jump to versions greater than 14.1 is not easy.

An alternative is ask to Ubuntu if they want to upgrade the version or backport the fix.

**Comment by marc-mabe** [comment]
* debian jessie = 2.2.5
* debian sid (unstable) = 2.2.7

**Comment by marc-mabe** [comment]
Because (currently) this adapter only supports string defined by our own capabilities I think the simplest fix would be to cast every input into a string before calling writing functions to redis.

As far as I can see in the redis source code it already supports serializing data into strings but for zend-cache this is a new future we can add this functionality in a future release that than needs to proper handle different versions of the installed redis extension.

**Comment by marc-mabe** [comment]
mh forget about my last comment this is more complicated:

Currently the capabilities describes that the redis adapter casts everything into strings.
This is not true!

In fact the adapter itself doesn't cast anything and gives the values as-is to the extension.
The extension **does** support serializing values but it needs to be configured to use a serializer.
By default no serializer is configured and yes in this case every value shoiuld be cast to a string by the extension but with the edge case that on storing `NULL` a segmentation fault happens in version 2.2.5.

I have a working PR #89 which fixes both because I'm sure if we blindly cast everything into a string only because the supported datatypes capability tells that it's still a BC break as it was working before.
