### ISSUE TITLE
there is no tag with 2.5.2 version but changelog says there should be this version

### ISSUE THREAD

**Issue by svycka** [zendframework/zend-cache#92]

**Comment by marc-mabe** [comment]
The tag is available here https://github.com/zendframework/zend-cache/tree/2.5.2 it's wrongly named as all other are named `release-<version>`

@weierophinney should we rename this tag?

**Comment by weierophinney** [comment]
@marc-mabe Yes. Do the following:

```console
$ git tag -s release-2.5.2 2.5.2
$ git tag -d 2.5.2
$ git push origin release-2.5.2:release-2.5.2
$ git push origin :2.5.2
```

That *should* work with Packagist, but ping me if you notice any issues.

**Comment by DCMNMarc** [comment]
@weierophinney ok I could do that. What about signing the tag(s)? I never signed a tag an am unsure what the process is.

**Comment by weierophinney** [comment]
It's pretty easy; create a gpg key, and git will prompt to ask which one to
use when signing. Ping me on irc tomorrow if you're having issues.

**Comment by marc-mabe** [comment]
fixed - thanks a lot @weierophinney
