### ISSUE TITLE
plugin by the name "exception_handler" was not found

### ISSUE THREAD

**Issue by Marat-Tanalin** [zendframework/zend-cache#97]
When trying to use zend-cache downloaded separately via Composer (under Windows 7, fwiw), the following exception is thrown:

> A plugin by the name "exception_handler" was not found in the plugin manager Zend\Cache\Storage\PluginManager

The relevant part of the stack trace:

> #0 ...\vendor\zendframework\zend-cache\src\StorageFactory.php(203): Zend\ServiceManager\AbstractPluginManager->get('exception_handl...')

`composer.json` used to download the package:

	{
		"name": "test",
		"require": {
			"zendframework/zend-cache": "^2.5"
		}
	}

In case of using zend-cache from ZF downloaded **entirely** (`"zendframework/zendframework": "^2.5"`), the issue is **not** reproduced.

Thanks.

**Comment by marc-mabe** [comment]
Thanks for your bug report - I can reproduce this bug -> the bug was introduced in 2.6.0 /:
We'll check how to fix this.

@weierophinney @ezimuel I think is has something todo with the server manager v2 / v3 compatibility - see #22 #69 

@Marat-Tanalin To fix your issue you should use camalCase or lower case but don't separate by `_`. `exception_handler` and `exceptionHandler` works fine

**Comment by marc-mabe** [comment]
@weierophinney @ezimuel Should we add also all underscore variants to the list of aliases?
-> this could be a lot as we have already a lot.

Current snipped just for 5 storage plugins:
```php
    protected $aliases = [
        'clearexpiredbyfactor' => Plugin\ClearExpiredByFactor::class,
        'clearExpiredByFactor' => Plugin\ClearExpiredByFactor::class,
        'ClearExpiredByFactor' => Plugin\ClearExpiredByFactor::class,
        'exceptionhandler'     => Plugin\ExceptionHandler::class,
        'exceptionHandler'     => Plugin\ExceptionHandler::class,
        'ExceptionHandler'     => Plugin\ExceptionHandler::class,
        'ignoreuserabort'      => Plugin\IgnoreUserAbort::class,
        'ignoreUserAbort'      => Plugin\IgnoreUserAbort::class,
        'IgnoreUserAbort'      => Plugin\IgnoreUserAbort::class,
        'optimizebyfactor'     => Plugin\OptimizeByFactor::class,
        'optimizeByFactor'     => Plugin\OptimizeByFactor::class,
        'OptimizeByFactor'     => Plugin\OptimizeByFactor::class,
        'serializer'           => Plugin\Serializer::class,
        'Serializer'           => Plugin\Serializer::class
    ];
```

**Comment by Marat-Tanalin** [comment]
If plugin names with underscore-separated words cannot be used anymore, documentation should probably account for this. Namely, `doc/book/storage/adapter.md` contains `exception_handler` multiple times.

**Comment by weierophinney** [comment]
> Should we add also all underscore variants to the list of aliases?

If they're commonly used, yes, we should add aliases for them, @marc-mabe ; do you want to do this? 

@Marat-Tanalin it's not that they cannot be used, but that zend-servicemanager v3 no longer does normalization. v2 would strip out non-alphanumeric characters from the service name to perform lookups, while v3 does strict literal matching. As such, if we create aliases using the most common separator characters, we can still use them.
